[package]
name = "schnorr_example_rust"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
candid = "=0.10.4"
ed25519-dalek = "2.1"
getrandom = { version = "0.2", features = ["custom"] }
hex = "0.4"
ic-cdk = "0.13"
k256 = { version = "0.12", features = ["ecdsa"] }
sha2 = "0.10"
schnorr_fun = "0.10"
serde = "1.0"
serde_bytes = "0.11"

[dev-dependencies]
pocket-ic = "2.2"