name: hosting-static-website
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - hosting/static-website/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
