name: hosting-unity-webgl
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/unity-webgl-template/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/hosting-unity-webgl-example.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
