name: motoko-hello_cycles
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/hello_cycles/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
