name: motoko-basic-bitcoin
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/basic_bitcoin/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-basic-bitcoin.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
