name: motoko-basic-dao
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/basic_dao/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-basic-dao-example.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
