name: motoko-encrypted-notes
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/encrypted-notes-dapp/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
