name: motoko-counter
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/counter/**
jobs:
  motoko-counter-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-counter-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
