name: motoko-threshold-ecdsa
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/threshold-ecdsa/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
