name: motoko-simple-to-do
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/simple-to-do/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
