name: motoko-random_maze
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/random_maze/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-random_maze-example.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
