name: motoko-dip721
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/dip721-nft-container/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
