name: motoko-pub-sub
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/pub-sub/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
jobs:
  motoko-pub-sub-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-pub-sub-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
