name: motoko-exchange-rate
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/exchange_rate/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
