name: motoko-invoice-canister
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/invoice-canister/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
