name: motoko-factorial
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/factorial/**
jobs:
  motoko-factorial-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-factorial-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'