name: motoko-superheroes
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-superheroes-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Superheroes Darwin
        run: |
          dfx start --background
          pushd motoko/superheroes
          make test
          popd
  motoko-superheroes-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Superheroes Linux
        run: |
          dfx start --background
          pushd motoko/superheroes
          make test
          popd
