name: motoko-phone-book
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/phone-book/**
jobs:
  motoko-phone-book-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-phone-book-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
