name: motoko-http_counter
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/http_counter/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
