name: motoko-hello-world
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/hello-world/**
jobs:
  motoko-hello-world-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-hello-world-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
