name: motoko-cert-var
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/cert-var/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-cert_var-example.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
