name: motoko-persistent-storage
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/persistent-storage/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
