name: motoko-invoice-canister
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/invoice-canister/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/motoko-invoice-unit.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
