name: motoko-basic-bitcoin
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/basic_bitcoin/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
