name: motoko-threshold-ecdsa
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-threshold-ecdsa-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Motoko Threshold ECDSA Darwin
        run: |
          dfx start --background
          pushd motoko/threshold-ecdsa
          dfx deploy
          bash test.sh
  motoko-threshold-ecdsa-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Motoko Threshold ECDSA Linux
        run: |
          dfx start --background
          pushd motoko/threshold-ecdsa
          dfx deploy
          bash test.sh
