name: motoko-dip721-example
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  motoko-dip721-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
        env:
          DFX_VERSION: 0.10.1
      - name: Motoko Defi Example Darwin
        run: |
          pushd motoko/dip721-nft-container
          bash ./demo.sh
          popd
  motoko-dip721-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
        env:
          DFX_VERSION: 0.10.1
      - name: Motoko Defi Example Linux
        run: |
          pushd motoko/dip721-nft-container
          bash ./demo.sh
          popd
