name: motoko-quicksort
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/quicksort/**
jobs:
  motoko-quicksort-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-quicksort-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
