name: motoko-echo
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - motoko/echo/**
jobs:
  motoko-echo-example-darwin:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
  motoko-echo-example-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
