name: rust-encrypted-notes
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - rust/encrypted-notes-dapp/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-encrypted-notes-example.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
