name: rust-tokens_transfer
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - rust/tokens_transfer/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
      - .github/workflows/rust-tokens-transfer-example.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
