name: rust-tokens_transfer
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - rust/tokens_transfer/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
