name: rust-basic-bitcoin
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rust-basic-bitcoin-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v1
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
      - name: Install ic-cdk-optimizer
        run: cargo install ic-cdk-optimizer
      - name: Rust Basic Bitcoin Darwin
        run: |
          pushd rust/basic_bitcoin
          dfx start --background
          dfx deploy basic_bitcoin --argument '(variant { Regtest })'
          popd
  rust-basic-bitcoin-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
      - name: Install ic-cdk-optimizer
        run: cargo install ic-cdk-optimizer
      - name: Rust Basic Bitcoin Linux
        run: |
          pushd rust/basic_bitcoin
          dfx start --background
          dfx deploy basic_bitcoin --argument '(variant { Regtest })'
          popd
