name: rust-pub-sub-example
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  rust-pub-sub-example-darwin:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Darwin
        run: bash .github/workflows/provision-darwin.sh
        env:
          DFX_VERSION: 0.10.0
      - name: Install ic-cdk-optimizer
        run: cargo install ic-cdk-optimizer
      - name: Rust Pub-Sub Example Darwin
        run: |
          pushd rust/pub-sub
          dfx start --background
          make install
          make test
          popd
  rust-pub-sub-example-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Provision Linux
        run: bash .github/workflows/provision-linux.sh
        env:
          DFX_VERSION: 0.10.0
      - name: Install ic-cdk-optimizer
        run: cargo install ic-cdk-optimizer
      - name: Rust Pub-Sub Example Linux
        run: |
          pushd rust/pub-sub
          dfx start --background
          make install
          make test
          popd
