name: rust-hello
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - rust/hello/**
      - .github/workflows/provision-darwin.sh
      - .github/workflows/provision-linux.sh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
