name: rust-pub-sub
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - rust/pub-sub/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Not needed - relevant folder not touched'
